kind: pipeline
name: build-develop

steps:
  - name: test
    image: maven:3.8.5-openjdk-17
    commands:
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B

trigger:
  branch:
    - develop

---
kind: pipeline
name: build-on-pull-request

steps:
  - name: test
    image: maven:3.8.5-openjdk-17
    commands:
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B

trigger:
  event:
    - pull_request